version: "3.8"

services:
  franchise-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: franchise_app
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always

