spring:
  application:
    name: franchise
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    name: ${DB_NAME}
server:
  port: 8080

